# Copyright (c) 2016 GigaSpaces Technologies Ltd. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

sudo: false

language: python

python:
  - '2.7'
  - '2.6'

env:
  - TOX_ENV=flake8
  - TOX_ENV=py27
  - TOX_ENV=py26

install:
  - if [ $TOX_ENV = py26 ]; then sudo add-apt-repository -y ppa:fkrull/deadsnakes && sudo apt-get update && sudo apt-get install python2.6 python2.6-dev; fi
  - pip install --upgrade pip
  - pip install tox

script:
  - pip --version
  - tox --version
  - PYTEST_PROCESSES=1 tox -e $TOX_ENV

# The PYTEST_PROCESSES environment var is used in tox.ini to override the --numprocesses argument
# for PyTest's xdist plugin. The reason this is necessary is that conventional Travis environments
# may report a large amount of available CPUs, but they they are greatly restricted. Through trial
# and error we found that more than 1 process may result in failures.
  